version: '3.0'
services:
  web:
    restart: 'always'
    build: .
    ports:
      - "8002:8000"
    depends_on:
      - db
    volumes:
      - ../db-data:/data
      - ../django-projects:/django-projects
      - ./setup.sh:/setup.sh
  db:
    restart: 'always'
    build: ./compose/db/
    ports:
      - '5432:5432'
    volumes:
      - ../db-data:/data
      - ./compose/db/initdb-postgis.sh:/docker-entrypoint-initdb.d/postgis.sh